1 4 basic template
thinknetica-django-lab-03/iamrealnurs pull request #13
Opened 2021-05-27 14:54 UTC by iamrealnurs

Сделал задания по заданию #8

2021-05-27 20:12 UTC, mikhailborodin requested changes

2021-05-27 20:12 UTC, mikhailborodin commented on avito/templates/base.html
> +      {{ flatpage.content }}
base.html является базовым шаблоном, в нем не может быть какого-то динамичного контента, максимум что в него добавляется это специальный тэг block который все шаблоны-наследники наполняют содержимым

2021-05-27 20:12 UTC, mikhailborodin commented on avito/templates/pages/index.html
> +<!DOCTYPE html>
index должен быть унаследован от base.html

2021-05-28 07:38 UTC, iamrealnurs commented on avito/templates/base.html
> +      {{ flatpage.content }}
Содержимое у шаблонов наследников должно заполняться в HTML из админки?

2021-05-28 11:38 UTC, merged