Создание Моделей
thinknetica-django-lab-03/iamrealnurs pull request #24
Opened 2021-06-03 15:19 UTC by iamrealnurs

В Этом ПР работаем над задачей #2

2021-06-03 20:26 UTC, mikhailborodin requested changes

2021-06-03 20:26 UTC, mikhailborodin commented on avito/main/models.py
> +        self.slug = slugify(self.title)
slugify не поддерживает кириллицу, он будет возвращать пустую строку `slugify('йцукен') --> ''`
отсюда и ошибка `django.db.utils.IntegrityError: UNIQUE constraint failed: main_category.slug`

2021-06-03 20:30 UTC, iamrealnurs commented on avito/main/models.py
> +        self.slug = slugify(self.title)
надо другую либу найти?

2021-06-05 09:15 UTC, mikhailborodin approved these changes

2021-06-05 09:59 UTC, merged